name: GitHub Actions Demo
run-name: ${{ github.actor }} está probando GitHub Actions 👍

on:
  push: 
    branches: [master]

jobs:
  Listar-Archivos:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lista los archivos del repositorio
        run: |
          ls ${{ github.workspace }}
